### ISSUE TITLE
AI: Tac-lights and lasers for zombies

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#63]
Given to zombies, for use in dark areas (demons have night-vision). Mostly to make them more visible to the player.

## Variants:
- Nightvision zombies: Equipped with a very dim green laser only visible under light-amp. Have a green glow or glowing goggles to make them more visible at range. 
- Laser zombies: Visible red laser slicing through the darkness. 
- Flashlight zombies: simple lights to let the player see where the zombies are.

Lasers would use elongated flatsprites, tac-lights would be a wide-spread low-radius spotlight, to keep performance manageable. Flashlights would also have a bright flare when pointed at the player.

Lasers / lights would be inventory items on the zombie that hook into angle/pitch and state/frame, Directionality would be via loose damped spring formulas, with "rest" positions set as offsets for zombies that aren't aiming.

## To-Do:

- [ ] Actual flashlight sprite "model" with large flare on front angle.
- [x] Linetrace out `x` units in front of monster to get sector light, instead of monster's current sector.
- [x] Start particle step at `i = 2` once sprite is done (don't need that superbright particle).
- [x] Make particle beam a little less aggressive?
  -Proper quadratic fading would actually be `alpha / ((i * spacing) ** 2)`
- [x] Target pos/rotation lower and down when monster not aiming (framecheck).
- [x] higher chance to toggle, and shortcut recheck when aiming (framecheck).
- [ ] Fix spastic lights on marines (issue #72)

**Comment by caligari87** [comment]
Flashlights (with visible beams!) added in f1dce94045e9f67766a3add1cd6a98c181490656.

TODO:

- [ ] Actual flashlight sprite "model" with large flare on front angle.
- [ ] Linetrace out `x` units in front of monster to get sector light, instead of monster's current sector.
- [ ] Start particle step at `i = 2` once sprite is done.
- [ ] Make particle beam a little less aggressive?

**Comment by caligari87** [comment]
Sort-of flashlight sprite added. Not sure I like it.

**Comment by caligari87** [comment]
Lasers and tac-lights working, considering this closed. Some bugs pending on #72
